[CmdletBinding()]
param([Parameter(Mandatory = $true)][string]$Task)
$ErrorActionPreference = 'Stop'
$root = [IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot))
$rootResolved = (Resolve-Path -LiteralPath $root).Path
$reportDir = Join-Path $root 'reports/agent-task'
$summaryPath = Join-Path $reportDir 'summary.json'
$model = 'gpt-5.6-luna'
$allowedTestScopes = @('BslOnly','EpfBuildOnly')
$maxRepairAttempts = 2
$codexExecutablePath = ''
$codexExecutableKind = ''
$agentRuns = @()
$testHistory = @()
New-Item -ItemType Directory -Force -Path $reportDir | Out-Null

function ConvertTo-ProcessArgument([string]$Argument) {
    if ($null -eq $Argument -or $Argument.Length -eq 0) { return '""' }
    if ($Argument -notmatch '[\s"]') { return $Argument }
    $b = New-Object Text.StringBuilder; [void]$b.Append([char]34); $slashes = 0
    foreach ($c in $Argument.ToCharArray()) {
        if ($c -eq [char]92) { $slashes++; continue }
        if ($c -eq [char]34) { if ($slashes -gt 0) { [void]$b.Append([char]92,(2*$slashes+1)) }; [void]$b.Append([char]34); $slashes=0; continue }
        if ($slashes -gt 0) { [void]$b.Append([char]92,$slashes) }; [void]$b.Append($c); $slashes=0
    }
    if ($slashes -gt 0) { [void]$b.Append([char]92,(2*$slashes)) }; [void]$b.Append([char]34); return $b.ToString()
}
function Invoke-NativeProcess([string]$FilePath,[string[]]$Arguments) {
    $s=New-Object Diagnostics.ProcessStartInfo; $s.FileName=$FilePath; $s.UseShellExecute=$false; $s.CreateNoWindow=$true; $s.RedirectStandardOutput=$true; $s.RedirectStandardError=$true
    if ($null -ne $s.PSObject.Properties['ArgumentList']) { foreach($a in $Arguments){[void]$s.ArgumentList.Add([string]$a)} } else { $s.Arguments=(($Arguments|ForEach-Object{ConvertTo-ProcessArgument ([string]$_)})-join ' ') }
    $p=New-Object Diagnostics.Process; $p.StartInfo=$s
    try { if(-not$p.Start()){throw 'Process could not be started.'};$o=$p.StandardOutput.ReadToEndAsync();$e=$p.StandardError.ReadToEndAsync();$p.WaitForExit();[pscustomobject]@{ExitCode=$p.ExitCode;StdOut=$o.Result;StdErr=$e.Result} } catch {[pscustomobject]@{ExitCode=1;StdOut='';StdErr=$_.Exception.ToString()}} finally {$p.Dispose()}
}
function Invoke-Git([string[]]$Arguments) { Invoke-NativeProcess $git.Source $Arguments }
function Get-CommandPath($CommandInfo) { if($CommandInfo.Path){[string]$CommandInfo.Path}else{[string]$CommandInfo.Source} }
function Get-Relative([string]$Path) {
    if([string]::IsNullOrWhiteSpace($Path)){return $null};$full=[IO.Path]::GetFullPath($Path);$r=$rootResolved.TrimEnd([char[]]@(92,47))
    if($full.Equals($r,[System.StringComparison]::OrdinalIgnoreCase)){return ''};if($full.StartsWith($r+[char]92,[System.StringComparison]::OrdinalIgnoreCase)-or$full.StartsWith($r+[char]47,[System.StringComparison]::OrdinalIgnoreCase)){return $full.Substring($r.Length).TrimStart([char[]]@(92,47)).Replace([char]92,[char]47)};return $full.Replace([char]92,[char]47)
}
function Existing([string]$Path) { if($Path -and (Test-Path -LiteralPath $Path -PathType Leaf)){Get-Relative $Path}else{$null} }
function Fingerprint([string]$Path) { if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){return $null};try{$i=Get-Item $Path;$h=(Get-FileHash $Path -Algorithm SHA256).Hash;"$($i.Length)|$($i.LastWriteTimeUtc.Ticks)|$h"}catch{$null} }
function Finish {
    param([string]$Status,[string]$Details,[string]$Branch,[string]$BranchAfter,[string]$HeadBefore,[string]$HeadAfter,[string]$TaskRelative,[string]$AgentStatus,[int]$AgentExitCode,[string]$TestStatus,[int]$TestExitCode,[object[]]$TestRuns,[object[]]$History=@())
    $changed=@();if($git){foreach($r in @((Invoke-Git @('-C',$root,'diff','--name-only')),(Invoke-Git @('-C',$root,'ls-files','--others','--exclude-standard')))){if($r.ExitCode -eq 0){$changed+=@($r.StdOut -split "`r?`n"|Where-Object{$_}|ForEach-Object{Get-Relative $_})}}}
    $logs=@();$add={param($p)$x=Existing $p;if($x -and $logs -notcontains $x){$logs+=$x}}
    foreach($a in @($agentRuns)){&$add $a.prompt;&$add $a.log;&$add $a.finalMessage}
    foreach($h in @($History)){foreach($t in @($h)){ $p=if($t.log){Join-Path $root $t.log}else{$null};&$add $p;$p=if($t.summary){Join-Path $root $t.summary}else{$null};&$add $p;foreach($d in @($t.diagnostics)){if($d){&$add (Join-Path $root $d)}}}}
    $s=[ordered]@{schemaVersion=3;status=$Status;details=$Details;branch=$Branch;git=[ordered]@{branchAfter=$BranchAfter;headBefore=$HeadBefore;headAfter=$HeadAfter};task=$TaskRelative;model=$model;maxRepairAttempts=$maxRepairAttempts;agent=[ordered]@{status=$AgentStatus;exitCode=$AgentExitCode;runs=@($agentRuns)};tests=[ordered]@{status=$TestStatus;exitCode=$TestExitCode;scopes=@($TestRuns);history=@($History)};changedFiles=@($changed);logs=@($logs)}
    $s|ConvertTo-Json -Depth 15|Set-Content $summaryPath -Encoding UTF8;Write-Host("Agent task status: {0}. {1}"-f$Status,$Details);if($Status-eq'passed'){exit 0};if($Status-eq'failed'){exit 1};exit 2
}

$taskInput=if([IO.Path]::IsPathRooted($Task)){$Task}else{Join-Path (Get-Location).Path $Task};$taskFull=[IO.Path]::GetFullPath($taskInput);$taskRel=Get-Relative $taskFull
if(-not(Test-Path $taskFull -PathType Leaf)){Finish 'blocked' "Task file not found: $taskRel" '' '' '' '' $taskRel 'not_run' 2 'not_run' 2 @()}
$taskResolved=(Resolve-Path -LiteralPath $taskFull).Path;$r=$rootResolved.TrimEnd([char[]]@(92,47));$inside=$taskResolved.Equals($r,[System.StringComparison]::OrdinalIgnoreCase)-or$taskResolved.StartsWith($r+[char]92,[System.StringComparison]::OrdinalIgnoreCase)-or$taskResolved.StartsWith($r+[char]47,[System.StringComparison]::OrdinalIgnoreCase)
if(-not$inside){Finish 'blocked' 'The task file must resolve inside the repository.' '' '' '' '' $taskResolved 'not_run' 2 'not_run' 2 @()};$taskFull=$taskResolved;$taskRel=Get-Relative $taskFull
$required=@('# Goal','# Context','# Requirements','# Acceptance criteria','# Allowed changes','# Forbidden changes','# Required tests');$taskContent=Get-Content -Raw $taskFull;$heads=@($taskContent -split "`r?`n"|Where-Object{$_-match '^# '}|ForEach-Object{$_.TrimEnd()});if(($heads-join "`n")-ne($required-join "`n")){Finish 'failed' 'Task headings are missing or out of order.' '' '' '' '' $taskRel 'not_run' 1 'not_run' 2 @()}
$m=[regex]::Match($taskContent,'(?ms)^# Required tests[ \t]*\r?\n(?<body>.*?)(?=^# |\z)');if(-not$m.Success){Finish 'blocked' 'The task must contain # Required tests.' '' '' '' '' $taskRel 'not_run' 2 'not_run' 2 @()};$body=[regex]::Replace($m.Groups['body'].Value,'(?s)<!--.*?-->','');$scopes=New-Object 'System.Collections.Generic.List[string]';$bad=$null;foreach($line in @($body -split "`r?`n")){ $line=$line.Trim();if(!$line){continue};if($line -notmatch '^- ([A-Za-z][A-Za-z0-9]*)$'){$bad=$line;break};$n=$Matches[1];if($allowedTestScopes-notcontains$n){$bad=$n;break};if(!$scopes.Contains($n)){[void]$scopes.Add($n)}};if($bad){Finish 'blocked' ("Unsupported or malformed required test scope: '{0}'. Allowed scopes: {1}."-f $bad,($allowedTestScopes-join ', ')) '' '' '' '' $taskRel 'not_run' 2 'not_run' 2 @()};if($scopes.Count-eq 0){Finish 'blocked' 'The # Required tests section must contain an allowlisted scope.' '' '' '' '' $taskRel 'not_run' 2 'not_run' 2 @()};$scopes=@($scopes)
$agentsPath=Join-Path $root 'AGENTS.md';if(-not(Test-Path $agentsPath -PathType Leaf)){Finish 'failed' 'AGENTS.md was not found.' '' '' '' '' $taskRel 'not_run' 1 'not_run' 2 @()};$agentsContent=Get-Content -Raw $agentsPath;if([string]::IsNullOrWhiteSpace($agentsContent)){Finish 'failed' 'AGENTS.md is empty.' '' '' '' '' $taskRel 'not_run' 1 'not_run' 2 @()}
$git=Get-Command git -ErrorAction SilentlyContinue;if(!$git){Finish 'blocked' 'Git is required.' '' '' '' '' $taskRel 'not_run' 2 'not_run' 2 @()};$repo=Invoke-Git @('-C',$root,'rev-parse','--show-toplevel');$repoRoot=$repo.StdOut.Trim();if($repo.ExitCode-ne 0-or !$repoRoot){Finish 'failed' ("Git repository detection failed: {0}"-f$repo.StdErr.Trim()) '' '' '' '' $taskRel 'not_run' 1 'not_run' 2 @()};if([IO.Path]::GetFullPath($repoRoot)-ne$root){Finish 'failed' 'The runner must execute from the repository root.' '' '' '' '' $taskRel 'not_run' 1 'not_run' 2 @()}
$b=Invoke-Git @('-C',$root,'branch','--show-current');$branch=$b.StdOut.Trim();if($b.ExitCode-ne 0-or!$branch){Finish 'failed' ("Git branch detection failed: {0}"-f$b.StdErr.Trim()) '' '' '' '' $taskRel 'not_run' 1 'not_run' 2 @()};if($branch-eq'main'){Finish 'blocked' 'The task runner is disabled on main.' $branch $branch '' '' $taskRel 'not_run' 2 'not_run' 2 @()};$wt=Invoke-Git @('-C',$root,'status','--porcelain=v1','--untracked-files=all');if($wt.ExitCode-ne 0){Finish 'failed' ("Git working tree inspection failed: {0}"-f$wt.StdErr.Trim()) $branch $branch '' '' $taskRel 'not_run' 1 'not_run' 2 @()};if(@($wt.StdOut -split "`r?`n"|Where-Object{$_}).Count-gt 0){Finish 'blocked' 'The working tree is not clean.' $branch $branch '' '' $taskRel 'not_run' 2 'not_run' 2 @()};$hb=Invoke-Git @('-C',$root,'rev-parse','--verify','HEAD');$headBefore=$hb.StdOut.Trim();if($hb.ExitCode-ne 0-or!$headBefore){Finish 'failed' 'Could not record HEAD.' $branch $branch '' '' $taskRel 'not_run' 1 'not_run' 2 @()}
$cmd=@(Get-Command codex.cmd -All -ErrorAction SilentlyContinue|Where-Object{$_.CommandType-eq'Application'})|Select-Object -First 1;$candidates=@();if($cmd){$codexExecutablePath=Get-CommandPath $cmd;$codexExecutableKind='codex.cmd (preferred)'}else{$candidates=@(Get-Command codex -All -ErrorAction SilentlyContinue);$native=@($candidates|Where-Object{$_.CommandType-eq'Application'-and(Get-CommandPath $_)-notmatch '(?i)\.ps1$'})|Select-Object -First 1;if($native){$codexExecutablePath=Get-CommandPath $native;$codexExecutableKind='codex native executable'}};if(!$codexExecutablePath){$script=@($candidates|Where-Object{$_.CommandType-eq'ExternalScript'-or(Get-CommandPath $_)-match '(?i)\.ps1$'})|Select-Object -First 1;if($script){Finish 'blocked' 'Only codex.ps1 was found; ExecutionPolicy will not be changed.' $branch $branch $headBefore $headBefore $taskRel 'blocked' 2 'not_run' 2 @()};Finish 'blocked' 'Codex CLI was not found on PATH.' $branch $branch $headBefore $headBefore $taskRel 'blocked' 2 'not_run' 2 @()}
$h1=&$codexExecutablePath --help 2>&1|Out-String;$e1=$LASTEXITCODE;$h2=&$codexExecutablePath exec --help 2>&1|Out-String;$e2=$LASTEXITCODE;$ht=$h1+"`n"+$h2;if($e1-ne 0-or$e2-ne 0-or$ht-notmatch'--model'-or$ht-notmatch'--sandbox'-or$ht-notmatch'--json'-or$ht-notmatch'--output-last-message'){Finish 'blocked' 'The selected Codex executable lacks required flags.' $branch $branch $headBefore $headBefore $taskRel 'blocked' 2 'not_run' 2 @()}
$ps=Get-Command pwsh -ErrorAction SilentlyContinue;if(!$ps){$ps=Get-Command powershell -ErrorAction SilentlyContinue};if(!$ps){Finish 'blocked' 'PowerShell is unavailable for selected tests.' $branch $branch $headBefore $headBefore $taskRel 'blocked' 2 'blocked' 2 @()};$testScript=Join-Path $root 'scripts/test.ps1';if(-not(Test-Path $testScript -PathType Leaf)){Finish 'blocked' 'scripts/test.ps1 is unavailable.' $branch $branch $headBefore $headBefore $taskRel 'blocked' 2 'blocked' 2 @()};$tracked=Join-Path $root 'reports/test-summary.json';$stub=Join-Path ([IO.Path]::GetTempPath()) 'stub_load_log.txt'
function ScopeConfig { param([string]$Name,[int]$Attempt);$suffix=if($Attempt-eq 0){''}else{"-repair-$Attempt"};switch($Name){'BslOnly'{[pscustomobject]@{Name=$Name;Arg='-BslOnly';Log=Join-Path $reportDir ("test-bsl{0}.log"-f$suffix);Summary=Join-Path $reportDir ("test-bsl{0}-summary.json"-f$suffix)}}'EpfBuildOnly'{[pscustomobject]@{Name=$Name;Arg='-EpfBuildOnly';Log=Join-Path $reportDir ("test-epf{0}.log"-f$suffix);Summary=Join-Path $reportDir ("test-epf{0}-summary.json"-f$suffix)}}default{throw "No test mapping for $Name"}}}
function RunScope { param($Config,[int]$Attempt);Remove-Item -Force -ErrorAction SilentlyContinue $Config.Log,$Config.Summary;$before=if($Config.Name-eq'EpfBuildOnly'){Fingerprint $stub}else{$null};$code=1;try{$o=@(&$ps.Source -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $testScript $Config.Arg 2>&1);$code=$LASTEXITCODE;$o|ForEach-Object{[string]$_}|Set-Content $Config.Log -Encoding UTF8}catch{Set-Content $Config.Log $_.Exception.ToString() -Encoding UTF8};$status='failed';if(Test-Path $tracked -PathType Leaf){try{$status=[string]((Get-Content -Raw $tracked|ConvertFrom-Json).status)}catch{$status='failed'}}elseif($code-eq 2){$status='blocked'};if($status-notin @('passed','failed','blocked')){$status=if($code-eq 2){'blocked'}else{'failed'}};$diag=@();if($Config.Name-eq'EpfBuildOnly'){$after=Fingerprint $stub;if($after-and$after-ne$before){$copy=Join-Path $reportDir ("epf-stub-load-attempt-{0}.log"-f$Attempt);Copy-Item $stub $copy -Force;$diag+=Get-Relative $copy}};[pscustomobject]@{scope=$Config.Name;status=$status;exitCode=$code;log=Existing $Config.Log;summary=Existing $Config.Summary;diagnostics=@($diag)}}
function RunSelected { param([int]$Attempt);$out=@();foreach($n in $scopes){$c=ScopeConfig $n $Attempt;Remove-Item -Force -ErrorAction SilentlyContinue $tracked;$x=RunScope $c $Attempt;if(Test-Path $tracked -PathType Leaf){Copy-Item $tracked $c.Summary -Force};$out+=$x};$out}
function TestStatus([object[]]$Runs){$s=@($Runs|ForEach-Object{$_.status});if($s-contains'blocked'-or$s-contains'not_run'){'blocked'}elseif($s-contains'failed'){'failed'}else{'passed'}}
function RunAgent { param([string]$Prompt,[int]$Attempt);$tag=if($Attempt-eq 0){'initial'}else{"repair-$Attempt"};$pp=Join-Path $reportDir "prompt-$tag.md";$lp=Join-Path $reportDir "codex-$tag.jsonl";$fp=Join-Path $reportDir "codex-$tag-final.md";Set-Content $pp $Prompt -Encoding UTF8;$old=@($env:GIT_CONFIG_COUNT,$env:GIT_CONFIG_KEY_0,$env:GIT_CONFIG_VALUE_0,$env:GIT_TERMINAL_PROMPT);$env:GIT_CONFIG_COUNT='1';$env:GIT_CONFIG_KEY_0='remote.origin.pushurl';$env:GIT_CONFIG_VALUE_0='DISABLED_BY_AGENT_TASK_RUNNER';$env:GIT_TERMINAL_PROMPT='0';$code=1;try{Push-Location $root;$o=@(Get-Content -Raw $pp|&$codexExecutablePath exec --model $model --sandbox workspace-write --json --output-last-message $fp - 2>&1);$code=$LASTEXITCODE;$o|Set-Content $lp -Encoding UTF8}catch{Set-Content $lp $_.Exception.ToString() -Encoding UTF8}finally{Pop-Location;foreach($i in 0..3){$names=@('GIT_CONFIG_COUNT','GIT_CONFIG_KEY_0','GIT_CONFIG_VALUE_0','GIT_TERMINAL_PROMPT');if($null-eq$old[$i]){Remove-Item "Env:$($names[$i])" -ErrorAction SilentlyContinue}else{Set-Item "Env:$($names[$i])" $old[$i]}}};$text=if(Test-Path $lp){Get-Content -Raw $lp}else{''};$status=if($code-eq 0){'passed'}elseif($text-match'(?i)(unknown model|unsupported.*model|invalid.*model)'){'blocked'}else{'failed'};[pscustomobject]@{attempt=$Attempt;status=$status;exitCode=$code;prompt=Existing $pp;log=Existing $lp;finalMessage=Existing $fp}}
function VerifyAgent { $h=Invoke-Git @('-C',$root,'rev-parse','--verify','HEAD');$b=Invoke-Git @('-C',$root,'branch','--show-current');[pscustomobject]@{ok=($h.ExitCode-eq 0-and$b.ExitCode-eq 0-and$h.StdOut.Trim()-eq$headBefore-and$b.StdOut.Trim()-eq$branch);head=$h.StdOut.Trim();branch=$b.StdOut.Trim()} }
$initialPrompt=@"
You are the implementation agent for the current repository.
Read and obey AGENTS.md and the selected task below. Work only on branch $branch.
Treat # Allowed changes and # Forbidden changes as authoritative. Do not make unrelated changes.
Do not run git push, git merge, create a pull request, switch to main, or commit. Run the selected allowlisted tests and make the minimum changes needed for the acceptance criteria.
The runner will execute only: $($scopes -join ', '). Do not claim success unless every selected scope passes.
===== AGENTS.md =====
$agentsContent
===== SELECTED TASK: $taskRel =====
$taskContent
"@;$initial=RunAgent $initialPrompt 0;$agentRuns+=@($initial);$v=VerifyAgent;$headAfter=$v.head;$branchAfter=$v.branch;if(-not$v.ok){Finish 'failed' 'HEAD or branch changed after initial Codex run.' $branch $branchAfter $headBefore $headAfter $taskRel $initial.status $initial.exitCode 'not_run' 2 @()};if($initial.status-eq'blocked'){Finish 'blocked' 'Initial Codex run was blocked.' $branch $branchAfter $headBefore $headAfter $taskRel 'blocked' $initial.exitCode 'not_run' 2 @()};if($initial.status-eq'failed'){Finish 'failed' 'Initial Codex run failed.' $branch $branchAfter $headBefore $headAfter $taskRel 'failed' $initial.exitCode 'not_run' 2 @()}
$testRuns=RunSelected 0;$testStatus=TestStatus $testRuns;$testHistory+=,@($testRuns);$attempt=0
while($testStatus-eq'failed'-and$attempt-lt$maxRepairAttempts){$attempt++;$lines=@("Repair attempt $attempt of $maxRepairAttempts.",'First inspect the existing diagnostic files listed below; do not paste or assume giant logs.','Fix the minimum cause, do not rewrite the whole solution without necessity, then re-check acceptance criteria.');foreach($x in $testRuns){$lines+="- $($x.scope): status=$($x.status)";if($x.log){$lines+="  log: $($x.log)"};if($x.summary){$lines+="  summary: $($x.summary)"};foreach($d in @($x.diagnostics)){if($d){$lines+="  diagnostic: $d"}}};$repairPrompt=@"
Repair the current repository after a failed selected test.
$($lines -join "`n")
Read the files above before editing. In particular, use the full EPF/1C diagnostic if present. Do not commit, push, merge, create a PR, or switch to main. Run the selected tests again.
===== AGENTS.md =====
$agentsContent
===== ORIGINAL TASK: $taskRel =====
$taskContent
"@;$repairRun=RunAgent $repairPrompt $attempt;$agentRuns+=@($repairRun);$v=VerifyAgent;$headAfter=$v.head;$branchAfter=$v.branch;if(-not$v.ok){Finish 'failed' 'HEAD or branch changed after repair; no further repair was attempted.' $branch $branchAfter $headBefore $headAfter $taskRel 'failed' $repairRun.exitCode $testStatus 1 $testRuns $testHistory};if($repairRun.status-eq'blocked'){Finish 'blocked' 'Repair agent was blocked; no further model run was attempted.' $branch $branchAfter $headBefore $headAfter $taskRel 'blocked' $repairRun.exitCode $testStatus 2 $testRuns $testHistory};if($repairRun.status-eq'failed'){Finish 'failed' 'Repair agent failed; no further repair was attempted.' $branch $branchAfter $headBefore $headAfter $taskRel 'failed' $repairRun.exitCode $testStatus 1 $testRuns $testHistory};$testRuns=RunSelected $attempt;$testStatus=TestStatus $testRuns;$testHistory+=,@($testRuns)}
$last=$agentRuns[-1];$exit=if($testStatus-eq'passed'){0}elseif($testStatus-eq'failed'){1}else{2};$overall=if($testStatus-eq'passed'){'passed'}elseif($testStatus-eq'failed'){'failed'}else{'blocked'};$detail=if($overall-eq'passed'){'Codex completed; all selected scopes passed.'}elseif($overall-eq'blocked'){'A selected scope was blocked; no further repair was attempted.'}{"Selected scopes still failed after $attempt repair attempt(s)."};Finish $overall $detail $branch $branchAfter $headBefore $headAfter $taskRel $last.status $last.exitCode $testStatus $exit $testRuns $testHistory
